### ISSUE TITLE
Postman collection is not found

### ISSUE THREAD

**Issue by hastarin** [ODataOrg/tutorials#2]
I'm unsure if this is the correct place to put this but hopefully whomever reads it will know.

On this page:
http://www.odata.org/getting-started/learning-odata-on-postman/

The URL for the Postman collection:
https://www.getpostman.com/collections/f5bc8732400d23f4ab7c

Gives an error:
{"error":"Collection not found"}

**Comment by dingeins** [comment]
@hastarin Yes this is. It looks that the collection URL is expired. We'll try to fix it.

**Comment by dingeins** [comment]
@hastarin It's fixed.
